account:
  name: account name
  mail: account mail
mysql:
  host: hostname
  user: username
  pass: password
  database: database
setting:
  hostname: localhost
  server:
    - name: main
      title: 偽津斗大学陸上競技部
      subdomain:
        - ~
        - www
        - main
      route: route.yml
    - name: admin
      title: 偽津斗大学陸上競技部
      subdomain:
        - admin
      route: admin.yml
      auth: true
