"":
  title: トップページ
  page: index

"competition":
  title: 試合日程／結果
  page: competition
  children:
    "year":
      children:
        "_num_":
          title: 試合日程
          page: competition/year
          var: year_id
    "competition":
      children:
        "_num_":
          title: 試合結果
          page: competition/competition
          var: com_id

"member":
  title: 部員一覧
  page: member
  children:
    "member":
      children:
        "_num_":
          title: 部員詳細
          page: member/member
          var: member_id

"record":
  title: 歴代記録
  page: record
  children:
    "_string_":
      title: 歴代記録
      page: record/gender
      var: gender_str

"special":
  children:
    "_num_":
      title: 特設ページ
      page: special
      var: special_id

"calendar":
  title: カレンダー
  page: calendar

"photo":
  title: 写真
  page: photo

"notice":
  title: 部内掲示板
  page: notice

"link":
  title: リンク
  page: link

"info":
  title: 連絡先／利用規約
  page: info
